# Generated by Django 3.2.3 on 2021-06-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.TextField(default='en-US', max_length=5),
        ),
        migrations.AddField(
            model_name='document',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
