# Generated by Django 3.2.4 on 2021-06-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0005_auto_20210606_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
