# Generated by Django 3.2.4 on 2021-06-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0007_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transcript',
            name='text_x',
            field=models.CharField(default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='transcript',
            name='text_y',
            field=models.CharField(default='bottom', max_length=10),
        ),
    ]
