# Generated by Django 3.2.4 on 2021-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0008_auto_20210617_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='height',
        ),
        migrations.RemoveField(
            model_name='document',
            name='width',
        ),
    ]
