# Generated by Django 3.2.4 on 2021-06-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0010_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='document',
            new_name='transcript',
        ),
    ]
