# Generated by Django 3.2.4 on 2021-06-22 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0011_rename_document_translation_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
