# Generated by Django 3.2.4 on 2021-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_subtitles', '0012_auto_20210622_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accessibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='public_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
